source "https://rubygems.org"

gem "jekyll", "~> 3.10.0"
gem "github-pages"
gem "kramdown-parser-gfm"
gem "jekyll-feed"
gem "jekyll-remote-theme"
gem "jekyll-mermaid"
gem "jekyll-toc"
gem "jekyll-asciidoc"
gem "jekyll-github-metadata"
gem "jekyll-seo-tag"
gem "jekyll-remote-theme"
gem "jekyll-coffeescript"
gem "jekyll-commonmark-ghpages"
gem "jekyll-gist"
gem "jekyll-github-metadata"
gem "jekyll-paginate"
gem "jekyll-relative-links"
gem "jekyll-optional-front-matter"
gem "jekyll-readme-index"
gem "jekyll-default-layout"
gem "jekyll-titles-from-headings"